# Generated by Django 6.0.3 on 2026-03-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominio_reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrador',
            name='statusConta',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Negado', 'Negado')], default='Pendente', max_length=50),
        ),
        migrations.AlterField(
            model_name='areacomum',
            name='statusLocal',
            field=models.CharField(choices=[('Disponivel', 'Disponível'), ('EmManutencao', 'Em Manutenção')], default='Disponivel', max_length=20),
        ),
        migrations.AlterField(
            model_name='morador',
            name='statusConta',
            field=models.CharField(choices=[('Pendente', 'Pendente'), ('Aprovado', 'Aprovado'), ('Negado', 'Negado')], default='Pendente', max_length=50),
        ),
    ]
